# More Crowdin's settings on: https://support.crowdin.com/configuration-file/#writing-a-simple-configuration-file
files:
  - source: /src/web/src/translations/es-*.md
    translation: /src/web/src/translations/%two_letters_code%-%original_file_name%.md
commit_message: "i18n-%language%: update %original_file_name%"
append_commit_message: false
