# More Crowdin's settings on: https://support.crowdin.com/configuration-file/#writing-a-simple-configuration-file
files:
  - source: /src/web/src/content/*.*
    translation: /src/web/src/content/%two_letters_code%-%file_name%.%file_extension%
    ignore:
      # - /src/web/src/content/%two_letters_code%_%original_file_name% # Ignore the source files.
      - /src/web/src/content/i18n.tsx
commit_message: "i18n-%language%: update %original_file_name%"
append_commit_message: false
